ansible_host: 141.5.107.139
ansible_python_interpreter: /usr/bin/python3

ufw_ports:
  - { rule: 'allow', port: '22', proto: 'tcp' }
  - { rule: 'allow', port: '80', proto: 'tcp' }
  - { rule: 'allow', port: '443', proto: 'tcp' }

ufw_apps:
  - { rule: 'allow', name: 'Apache Full' }

venv_path: /home/cloud/myproject/myprojectenv

domain: 'flask-edu-test.tk'

www-domain: 'www.flask-edu-test.tk'

admin-mail: 'sroertg@gwdg.de'

mysql:
  user: root
  old_password: ""
  new_password: 123123
  hosts:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"
  privileges: "*.*:ALL,GRANT"

wp_db_name: wordpress
wp_db_user: wordpressuser
wp_db_pass: 12345
wp_db_priv: '*.*:ALL'
