- name: Check if WordPress directory exists in /var/www
  stat: path=/var/www/wordpress
  register: check_path

- name: Check if Upgrade directory already exists in /tmp/wordpress/wp-content/upgrade
  stat: path=//tmp/wordpress/wp-content/upgrade
  register: check_upgrade_path

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
#    checksum: ""
  when: not check_path.stat.exists

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no
  when: not check_path.stat.exists
  become: yes

- name: touch .htaccess
  file:
    path: /tmp/wordpress/.htaccess
    state: touch
    owner: www-data
    group: www-data
  when: not check_path.stat.exists
  become: yes

- name: Copy WordPress-config
  copy:
    remote_src: yes
    src: /tmp/wordpress/wp-config-sample.php
    dest: /tmp/wordpress/wp-config.php
    owner: www-data
    group: www-data
  when: not check_path.stat.exists
  become: yes

- name: Make Wordpress upgrade directory
  file:
    path: /tmp/wordpress/wp-content/upgrade
    state: directory
    owner: www-data
    group: www-data
  when: not check_upgrade_path.stat.exists
  become: yes

- name: Move WordPress install files
  command: mv /tmp/wordpress /var/www/wordpress
  args:
    creates: /var/www/wordpress
  when: not check_path.stat.exists
  become: yes

- name: get keys
  command: curl -s https://api.wordpress.org/secret-key/1.1/salt/
  register: key_files

- name: Copy wp-config.php
  template:
    src: wp-config.php
    dest: /var/www/wordpress/wp-config.php
    owner: www-data
    group: www-data
  become: yes
