---
moodle_host: "{{hostvars['web_server']['ansible_host']}}"
moodle_url: "http://{{ hostvars['web_server']['moodle_url']}}"
moodle_archive_url: https://download.moodle.org/download.php/direct/stable37/moodle-3.7.tgz
download_dir: "/home/{{ ansible_user }}"
edu_sharing_plugin_dir: "{{ download_dir }}/plugin-moodle-4.2"
moodle_data_dir: /var/moodledata
moodle_root_dir: /var/www

moodle_admin_user: admin
moodle_admin_password: asd456
moodle_admin_email: ab@c.de

moodle_fullname: "Moodle-Test-BOX"
moodle_shortname: "moodle-box"
moodle_summary: "Eine_virtuelle_Box_um_Moodle_zu_testen."

mariadb_port: 3306
moodle_db:
  name: moodle
  user: moodle
  password: moodle

edu_sharing_host: "{{hostvars['web_server']['edu_sharing_host']}}"
edu_sharing_base_domain: "{{hostvars['web_server']['edu_sharing_base_domain']}}"
edu_sharing_url: "{{ hostvars['web_server']['edu_sharing_base_domain'] }}/edu-sharing"
edusharing_plugin_url: "{{ hostvars['web_server']['edusharing_plugin_url'] }}"

base_dir: "{{ansible_env.HOME}}"