---
- block:
  - import_tasks: include-vars.yml

  - name: check if certbot certificate is already installed
    stat: path=/etc/apache2/sites-enabled/wordpress-le-ssl.conf
    register: check_cert

  - import_tasks: install-with-package.yml
    when:
      - not certbot_install_from_source

  - import_tasks: install-from-source.yml
    when:
      - certbot_install_from_source

  - include_tasks: create-cert-standalone.yml
    with_items: "{{ certbot_certs }}"
    when:
#      - not check_cert.stat.exists
      - certbot_create_if_missing
      - certbot_create_method == 'standalone'
    loop_control:
      loop_var: cert_item

#  - name: Check if cron job already exists

  - import_tasks: renew-cron.yml
    when:
      - certbot_auto_renew

  become: yes
