ansible_host: 141.5.107.139
ansible_python_interpreter: /usr/bin/python3
ansible_connection: ssh
ansible_ssh_extra_args: -o StrictHostKeyChecking=no
ansible_user: cloud
ansible_ssh_pass: uWPb0qtX
ansible_become_pass: '{{ ansible_ssh_pass }}'
moodle_url: 'http://{{ moodle_base_domain }}'
moodle_base_domain: c107-138.cloud.gwdg.de

edu_sharing_host: 192.168.98.101
edu_sharing_base_domain: http://192.168.98.101
edu_sharing_url: "http://{{ edu_sharing_base_domain }}/edu-sharing"
edusharing_plugin_url: https://github.com/edu-sharing/plugin-moodle/archive/4.2.tar.gz

base_dir: "{{ansible_env.HOME}}"