ansible_host: 141.5.107.139
edu_sharing_domain: '{{edu_sharing_base_domain}}'
ansible_connection: ssh
ansible_ssh_extra_args: -o StrictHostKeyChecking=no
ansible_user: cloud
ansible_ssh_pass: suPgwc0E
ansible_become_pass: '{{ ansible_ssh_pass }}'
edu_sharing_url: 'http://{{ edu_sharing_base_domain}}/edu-sharing'
edu_sharing_base_domain: c107-139.cloud.gwdg.de