---
# defaults file for mysql

# The address mysql should bind to.
mysql_bind_address: 127.0.0.1

# This role can populate databases and users, see below.
# mysql_databases:
#   - name: firstdb
#   - name: seconddb
#
mysql_users:
  name: "{{ mysql['user'] }}"
  password: "{{ mysql['new_password'] }}"
  priv: "{{ mysql['privileges'] }}"
  host: "{{ mysql['hosts'] }}"
