---
- hosts: web_server
  become: yes
  roles:
    - set-timezone
    - python
    - mariadb
    - apache
    - moodle
  tags:
    - root-task

- hosts: web_server
  become: yes
  roles: 
    - edu-sharing-plugin
  tags:
    - edu-sharing-plugin

#    - certbot
