---
  - name: Create WP-Database
    mysql_db:
      login_user: "{{ mysql['user'] }}"
      login_password: "{{ mysql['new_password'] }}"
      name: "{{ wp_db_name }}"
      state: present
    become: yes

  - name: Create WP-User
    mysql_user:
      login_user: "{{ mysql['user'] }}"
      login_password: "{{ mysql['new_password'] }}"
      name: "{{ wp_db_user }}"
      host: localhost
      password: "{{ wp_db_pass }}"
      priv: "{{ wp_db_priv }}"
      state: present
    become: yes

  - name: Restart MySql
    service:
      name: mysql
      state: restarted
    become: yes
