---
  - name: Copy mysqld.cnf
    template:
      src: mysqld.cnf
      dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    become: yes

  - name: Restart MySQL
    service:
      name: mysql
      state: restarted
    become: yes

  - name: Create App-Database
    mysql_db:
      login_user: "{{ hostvars['web_server']['mysql']['user'] }}"
      login_password: "{{ hostvars['web_server']['mysql']['new_password'] }}"
      name: "{{ hostvars['web_server']['app_db_name']}}"
      encoding: '{{ mysql_encoding }}'
      collation: '{{ mysql_collate }}'
      state: present
    become: yes

  - name: Create App-DB-User
    mysql_user:
      login_user: "{{ hostvars['web_server']['mysql']['user'] }}"
      login_password: "{{ hostvars['web_server']['mysql']['new_password'] }}"
      name: "{{ hostvars['web_server']['app_db_user']}}"
      host: localhost
      password: "{{ hostvars['web_server']['app_db_pass']}}"
      priv: "{{ hostvars['web_server']['app_db_priv']}}"
      state: present
    become: yes

  - name: Restart MySql
    service:
      name: mysql
      state: restarted
    become: yes
