---
# vars file for mysql
_mysql_packages:
  default:
    - mariadb-server
    - mariadb-devel
    - python-devel
    - python2-mysql
  Alpine:
    - mariadb
    - python-dev
    - py-mysqldb
  Archlinux:
    - mariadb
  CentOS-6:
    - mysql-devel
    - mysql-server
    - MySQL-python
    - python-devel
  CentOS-7:
    - mariadb-devel
    - mariadb-server
    - MySQL-python
    - python-devel
  Debian:
    - mariadb-server
    - python-dev
    - python-mysqldb
  Fedora:
    - mariadb-server
    - mariadb-devel
    - python-devel
    - python2-mysql
  Ubuntu:
    - mariadb-server
    - libssl-dev
    - python-dev
    - python-mysqldb
  openSUSE Leap:
    - libmysqlclient-devel
    - mariadb
    - python-devel
    - python-MySQL-python

mysql_packages: "{{ _mysql_packages[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_mysql_packages[ansible_distribution] | default(_mysql_packages['default'])) }}"

_mysql_service:
  default: mysql
  Alpine: mariadb
  Archlinux: mariadb
  CentOS-6: mysqld
  CentOS-7: mariadb
  Fedora: mariadb

mysql_service: "{{ _mysql_service[ansible_distribution ~ '-' ~ ansible_distribution_major_version] | default(_mysql_service[ansible_distribution] | default(_mysql_service['default'])) }}"
